title = "AStarPathfinding"  # From Git
gitRepoUrl = "https://github.com/Daemon6109/astarpathfinding" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "Daemon6109"
projectName = "AStarPathfinding"
url = "https://Daemon6109.github.io/"
baseUrl = "/AStarPathfinding"

[footer]
style = "dark"

[[footer.links]]
title = "AStarPathfinding"

[home]
enabled = true
includeReadme = true # Optional