title = "AStarPathfinding"
gitRepoUrl = "https://github.com/Daemon6109/astarpathfinding"
gitSourceBranch = "main"
changelog = true

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
organizationName = "Daemon6109"
projectName = "AStarPathfinding"
url = "https://Daemon6109.github.io/"
baseUrl = "/AStarPathfinding"

[footer]
style = "dark"

[[footer.links]]
title = "AStarPathfinding"

[home]
includeReadme = true