[package]
name = "daemon6109/astar-pathfinding"
description = "Deterministic grid-based A* pathfinding for Roblox and Luau."
version = "1.1.2"
license = "MIT"
authors = ["Matthew Radulovich (Daemon6109)"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Daemon6109/AStarPathfinding"
include = ["src/AStarPathfinding/**", "README.md", "LICENSE"]
exclude = [
	".darklua.json",
	".gitattributes",
	".gitignore",
	".luaurc",
	".stylua.toml",
	".github/**",
	"build.project.json",
	"dev.project.json",
	"moonwave.toml",
	"pesde.toml",
	"rokit.toml",
	"scripts/**",
	"scripts",
	"selene.toml",
	"selene_definitions.yml",
	"src/__tests__/**",
	"src/__tests__",
	"src/jest.config.luau",
]

[dependencies]
